### PR TITLE
SVCPLAN-5555: Add support for SUSE

### PR DESCRIPTION
**Pull request by billglick**
This is being tested on `control-test-opensuse155a`.

### CODE REVIEW

**Review by jakerundall — APPROVED** [review]
Looks good. We could revisit defining a zypper repo later on (instead of installing the release RPM).

**Comment by billglick** [comment]
@jakerundall Perhaps you should re-review this pull request.

I updated this profile to use the zypprepo module for SUSE. I refactored the RedHat stuff as well, changing `yumrepo` to a more generic `repos` parameter. And I also had to add some exec to the SUSE side of things to install the gpgkey if it points to a URL.

**Review by jakerundall — COMMENTED** [review]
This all looks good, I would just highlight the change from `yumrepo` to `repos` a bit more, e.g.:

(1) Make the first line of the commit message be something like "<TICKET-ID>: BREAKING ..."

(2) Add a note in README.md.

Thoughts?

**Comment by billglick** [comment]
> (1) Make the first line of the commit message be something like ": BREAKING ..."
> 
> (2) Add a note in README.md.

@jakerundall I made these 2 suggested changes. Let me know if they communicate as expected.

And once merged I will iterate the tag to `v0.2.0` to denote a significant change.

**Review by jakerundall — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
